# Generated by Django 5.0 on 2024-04-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_scoreboard', models.IntegerField()),
                ('visiting_scoreboard', models.IntegerField()),
                ('game', models.IntegerField()),
                ('home_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_coach', to='table.coach')),
                ('home_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_formation', to='table.formation')),
                ('visiting_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_coach', to='table.coach')),
                ('visiting_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_formation', to='table.formation')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.stadium')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='table.team')),
                ('visiting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team', to='table.team')),
            ],
        ),
    ]
